//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Dizimos")]
    public partial class Dizimo
    {
        [Key]
        [DisplayName("Id")]
        public int Id_Dizimo { get; set; }
        [DisplayName("Membro")]
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public int Id_Membros { get; set; }
        [DisplayName("Mês Referência")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/yyyy}", HtmlEncode = true)]
        public DateTime Mes_Ref { get; set; }
        [DisplayName("Data Movimento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}", HtmlEncode = true)]
        public DateTime Dt_Mov { get; set; }
        [DisplayName("Valor")]
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public decimal Vl_Dizimo { get; set; }

        public virtual Membro Membros { get; set; }
    }
}
