//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Departamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departamentos()
        {
            this.Principal = true;
            this.Ativo = true;
            this.Agendas = new HashSet<Agendas>();
            this.Lancamentos = new HashSet<Lancamentos>();
            this.Lancamentos1 = new HashSet<Lancamentos>();
            this.Memb_Depto = new HashSet<Memb_Depto>();
        }

        public int Id_Deptos { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        [MaxLength(30, ErrorMessage = "Campo deve conter no máximo 30 caracteres.")]
        public string Nm_Deptos { get; set; }
        [DefaultValue(true)]
        public bool Principal { get; set; }
        [DefaultValue(true)]
        public bool Ativo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendas> Agendas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lancamentos> Lancamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lancamentos> Lancamentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memb_Depto> Memb_Depto { get; set; }
    }
}
