//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Lancamentos
    {
        public string Id_Lanc { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public int Id_Deptos { get; set; }
        public int Id_Deptos_Receber { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public int Id_Tp_Lanc { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public string Tpo_Mov { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public string Tpo_pag { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public decimal Vl_Lanc { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        [MaxLength(30, ErrorMessage = "Campo deve conter no máximo 30 caracteres.")]
        public string Desc_Lanc { get; set; }
        [DefaultValue(1)]
        public int Qtd_Parc_Lanc { get; set; }
        public DateTime Dt_Lanc { get; set; }
        public DateTime Dt_Mov { get; set; }
        public DateTime Dt_Venc { get; set; }
        public string Obs { get; set; }
        [DefaultValue(true)]
        public bool Faturado { get; set; }

        public virtual Departamentos Departamentos { get; set; }
        public virtual Departamentos Departamentos1 { get; set; }
        public virtual Tipos_Lancamentos Tipos_Lancamentos { get; set; }
    }
}
