//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Memb_Familiares
    {
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public int Id_Memb { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public int Id_Memb_Familiar { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        [MaxLength(15, ErrorMessage = "Campo deve conter no máximo 15 caracteres.")]
        public string Parentesco { get; set; }
    
        public virtual Membros Membros { get; set; }
        public virtual Membros Membros1 { get; set; }
    }
}
