//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Membros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membros()
        {
            this.Disciplinas = new HashSet<Disciplinas>();
            this.Dizimos = new HashSet<Dizimos>();
            this.Memb_Depto = new HashSet<Memb_Depto>();
            this.Memb_Familiares = new HashSet<Memb_Familiares>();
            this.Memb_Familiares1 = new HashSet<Memb_Familiares>();
        }

        public int Id_Membros { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public int Id_Cargo { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public int Id_Status { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        [MaxLength(50, ErrorMessage = "Campo deve conter no máximo 50 caracteres.")]
        public string Nome { get; set; }
        [MaxLength(50, ErrorMessage = "Campo deve conter no máximo 50 caracteres.")]
        public string Mae { get; set; }
        [MaxLength(50, ErrorMessage = "Campo deve conter no máximo 50 caracteres.")]
        public string Pai { get; set; }
        public string Sexo { get; set; }
        public string Matricula { get; set; }
        public DateTime Dt_Nasc { get; set; }
        public DateTime Dt_Desde { get; set; }
        [DefaultValue(true)]
        public bool Ativo { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Email { get; set; }
        public string Cep { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Uf { get; set; }
        public int N_Casa { get; set; }
        public string Foto { get; set; }
        public string Obs { get; set; }

        public virtual Cargos Cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disciplinas> Disciplinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dizimos> Dizimos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memb_Depto> Memb_Depto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memb_Familiares> Memb_Familiares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memb_Familiares> Memb_Familiares1 { get; set; }
        public virtual Status Status { get; set; }
    }
}
